version: '3'
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
      target: dev
    image: next-app-dev:1.0.0
    container_name: next-app-dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true